from django.urls import path
from . import views

app_name = "canvas"

urlpatterns = [
    path("", views.index, name="index"),
    path("add-partnership",
         views.addPartnership, name="add-partnership"),
    path("partnerships/<int:id>/delete",
         views.deletePartnership, name="delete-partnership"),
    path("add-activity",
         views.addActivity, name="add-activity"),
    path("activities/<int:id>/delete",
         views.deleteActivity, name="delete-activity"),
    path("add-resource",
         views.addResource, name="add-resource"),
    path("resources/<int:id>/delete",
         views.deleteResource, name="delete-resource"),
    path("add-proposition",
         views.addProposition, name="add-proposition"),
    path("propositions/<int:id>/delete",
         views.deleteProposition, name="delete-proposition"),
    path("add-customer-relationship",
         views.addCustomerRelationship, name="add-customer-relationship"),
    path("customer-relationships/<int:id>/delete",
         views.deleteCustomerRelationship, name="delete-customer-relationship"),
    path("add-channel",
         views.addChannel, name="add-channel"),
    path("channels/<int:id>/delete",
         views.deleteChannel, name="delete-channel"),
    path("add-customer-segment",
         views.addCustomerSegment, name="add-customer-segment"),
    path("customer-segments/<int:id>/delete",
         views.deleteCustomerSegment, name="delete-customer-segment"),
    path("add-cost-structure",
         views.addCostStructure, name="add-cost-structure"),
    path("cost-structures/<int:id>/delete",
         views.deleteCostStructure, name="delete-cost-structure"),
    path("add-revenue-stream",
         views.addRevenueStream, name="add-revenue-stream"),
    path("revenue-streams/<int:id>/delete",
         views.deleteRevenueStream, name="delete-revenue-stream"),
    path("about", views.about, name="about"),
    path("features", views.features, name="features"),
    path("contact", views.contact, name="contact"),
]
